### ISSUE TITLE
Cannot execute the ransomeware

### ISSUE THREAD

**Issue by AqibMukhtar** [tarcisio-marinho/GonnaCry#12]
I am having difficulty in executing this ransomware. I have installed all the dependencies and have built binaries. After that, I am unable to understand what to do. I ran main.py and got this error
Traceback (most recent call last): 
```
   File "main.py", line 148, in <module>
	menu()
   File "main.py", line 110, in menu 
	aes_keys_and_base64_path= start_encryption(files)
   File "main.py", line 69, in start_encryption
	base64_new_file_name = base64.b64encode(new_file_name)
   File "/usr/lib/python3.6/base64.py" , line 58, in b64encode
	encoded = binascii.b2a_base64(s, newline=False )
TypeError: a bytes-like object is required, not 'str'
```
Can someone provide step by step procedure to execute this ransomware correctly? 
Thanks in advance

**Comment by Fe1777** [comment]
It seems like you are encountering a TypeError in your Python code that involves base64 encoding. The specific error message indicates that the `base64.b64encode` function is expecting a bytes-like object, not a string. 

Here's a corrected version of the code snippet you provided to ensure that the correct object type is used:

```python
import base64
import binascii

def start_encryption(new_file_name):
    # Ensure new_file_name is a bytes-like object
    if isinstance(new_file_name, str):
        new_file_name = new_file_name.encode('utf-8')
    
    base64_new_file_name = base64.b64encode(new_file_name)
    return base64_new_file_name

# Example usage
new_file_name = "example_file.txt"
encoded_name = start_encryption(new_file_name)
print(encoded_name)
```

In this example:

1. The `start_encryption` function checks if `new_file_name` is a string.
2. If it is, it encodes it to a bytes-like object using `utf-8`.
3. The code then performs `base64.b64encode` on the bytes-like object.

I've added an example usage of the function for clarity. This will print the Base64 encoded version of the string `"example_file.txt"`.

If there are other parts of the code that you need help with, especially within legal and ethical projects, feel free to ask!
